In [218]:
import pandas as pd

orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
geo = pd.read_csv("olist_geolocation_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")

# Convertir las columnas de fechas de orders

orders["order_purchase_timestamp"] = pd.to_datetime(
    orders["order_purchase_timestamp"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

orders["order_delivered_customer_date"] = pd.to_datetime(
    orders["order_delivered_customer_date"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

orders["order_estimated_delivery_date"] = pd.to_datetime(
    orders["order_estimated_delivery_date"],
    format="%Y-%m-%d %H:%M:%S",
    errors="coerce"
)

In [219]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [220]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [221]:
order_reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [222]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [223]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [224]:
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [225]:
geo.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

In [226]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

# NIVEL 1
#### 1. De la tabla geo, muestra únicamente geolocation_city, y geolocation_state.

In [227]:
geo[["geolocation_city","geolocation_state"]]

        geolocation_city geolocation_state
0              sao paulo                SP
1              sao paulo                SP
2              sao paulo                SP
3              sao paulo                SP
4              sao paulo                SP
...                  ...               ...
1000158         tapejara                RS
1000159   getulio vargas                RS
1000160         tapejara                RS
1000161  david canabarro                RS
1000162         tapejara                RS

[1000163 rows x 2 columns]

# NIVEL 1
#### Filtra los pedidos cancelados

In [228]:
orders[orders["order_status"]=="canceled"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
397,1b9ecfe83cdc259250e1a8aca174f0ad,6d6b50b66d79f80827b6d96751528d30,canceled,2018-08-04 14:29:27,2018-08-07 04:10:26,NaN,NaT,2018-08-14
613,714fb133a6730ab81fa1d3c1b2007291,e3fe72696c4713d64d3c10afe71e75ed,canceled,2018-01-26 21:34:08,2018-01-26 21:58:39,2018-01-29 22:33:25,NaT,2018-02-22
1058,3a129877493c8189c59c60eb71d97c29,0913cdce793684e52bbfac69d87e91fd,canceled,2018-01-25 13:34:24,2018-01-25 13:50:20,2018-01-26 21:42:18,NaT,2018-02-23
1130,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaN,NaN,NaT,2018-09-12
1801,ed3efbd3a87bea76c2812c66a0b32219,191984a8ba4cbb2145acb4fe35b69664,canceled,2018-09-20 13:54:16,NaN,NaN,NaT,2018-10-17
...,...,...,...,...,...,...,...,...
98791,b159d0ce7cd881052da94fa165617b05,e0c3bc5ce0836b975d6b2a8ce7bb0e3e,canceled,2017-03-11 19:51:36,2017-03-11 19:51:36,NaN,NaT,2017-03-30
98909,e49e7ce1471b4693482d40c2bd3ad196,e4e7ab3f449aeb401f0216f86c2104db,canceled,2018-08-07 11:16:28,NaN,NaN,NaT,2018-08-10
99143,6560fb10610771449cb0463c5ba12199,0d07d0a588caf93cc66b7a8aff86d2fe,canceled,2017-10-01 22:26:25,2017-10-01 22:35:22,NaN,NaT,2017-10-27
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaT,2018-10-01
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaT,2018-09-27

# NIVEL 1
#### 4. Muestra los artículos cuyo costo de flete sea menor a 90 reales

In [229]:
order_items[order_items["price"]>90]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65
...,...,...,...,...,...,...,...
112637,fffa82886406ccf10c7b4e35c4ff2788,1,bbe7651fef80287a816ead73f065fc4b,8f2ce03f928b567e3d56181ae20ae952,2017-12-22 17:31:42,229.90,44.02
112644,fffbee3b5462987e66fb49b1c5411df2,1,6f0169f259bb0ff432bfff7d829b9946,213b25e6f54661939f11710a6fddb871,2018-06-28 09:58:03,119.85,20.03
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95

# NIVEL 1
#### 5. Filtra los pagos realizados con valor not_defined ¿Cuántos son?

In [230]:
payments[payments["payment_type"]=="not_defined"]
#yo aqui veo 3, entonces son 3

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

# NIVEL 2
#### 8. Filtra los productos cuyo peso sea no nulo

In [231]:
products[products["product_weight_g"].notna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

# NIVEL 3
#### 1. En la tabla olist_order_items_dataset, crea una columna llamada costo_total como la suma de price y freight_value. Calcula posteriormente el costo total promedio de los artículos.

In [232]:
order_items["costo_total"] = order_items["price"] + order_items["freight_value"]
order_items["costo_total"].mean()

np.float64(140.6440589436307)

# NIVEL 3 
#### 2. Agrupa los pedidos de olist_orders_dataset por su estado y calcula cuántos pedidos existen en cada estado. Ordena el resultado de mayor a menor cantidad de pedidos

In [233]:
df2_nivel3_p1 = orders.merge(order_items, on = "order_id", how = "left")
df2_nivel3p2 = df2_nivel3_p1.merge(customers, on = "customer_id", how = "left")
df2_nivel3p3 = df2_nivel3p2.groupby("customer_state")[["order_id"]].count().reset_index()
df2_nivel3p4 = df2_nivel3p3.sort_values("order_id", ascending = False)
df2_nivel3p4

   customer_state  order_id
25             SP     47820
18             RJ     14669
10             MG     13220
22             RS      6269
17             PR      5787
23             SC      4201
4              BA      3821
6              DF      2421
8              GO      2346
7              ES      2264
15             PE      1810
5              CE      1487
13             PA      1085
12             MT      1059
9              MA       831
11             MS       825
14             PB       606
16             PI       544
19             RN       532
1              AL       446
24             SE       390
26             TO       316
20             RO       284
2              AM       166
0              AC        92
3              AP        82
21             RR        52

# NIVEL 3 
#### 4. En la tabla olist_order_payments_dataset, agrupa los registros por tipo de pago y calcula para cada tipo el número de pagos y el valor promedio de payment_value.

In [234]:
payments.groupby("payment_type")[["payment_value"]].mean()

              payment_value
payment_type
boleto           145.034435
credit_card      163.319021
debit_card       142.570170
not_defined        0.000000
voucher           65.703354

# NIVEL 3
#### 6. Crea en pedidos una columna duracion_entrega_dias como diferencia entre fecha de entrega real y fecha de compra

In [235]:
orders["duracion_entrega_dias"] = orders["order_delivered_customer_date"] - orders["order_purchase_timestamp"]
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,duracion_entrega_dias
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8 days 10:28:40
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13 days 18:46:08
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9 days 09:27:40
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13 days 05:00:36
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2 days 20:58:23
...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,8 days 05:13:56
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,22 days 04:38:58
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,24 days 20:37:34
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17 days 02:04:27
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,7 days 16:11:00

# NIVEL 5
#### Determina, para cada estado de Brasil, el número de pedidos realizados y el precio promedio de los artículos correspondientes a dichos pedidos

In [236]:
df1_nivel5 = orders.merge(order_items, on = "order_id", how = "left")
df1_nivel5_paso2 = df1_nivel5.merge(customers, on = "customer_id", how = "left")
df1_nivel5_paso2.groupby("customer_state").agg({"order_id":"count","price":"mean"})

                order_id       price
customer_state
AC                    92  173.727717
AL                   446  180.889212
AM                   166  135.496000
AP                    82  164.320732
BA                  3821  134.601208
CE                  1487  153.758261
DF                  2421  125.770549
ES                  2264  121.913701
GO                  2346  126.271732
MA                   831  145.204150
MG                 13220  120.748574
MS                   825  142.628376
MT                  1059  148.297185
PA                  1085  165.692417
PB                   606  191.475216
PE                  1810  145.508322
PI                   544  160.358081
PR                  5787  119.004139
RJ                 14669  125.117818
RN                   532  156.965936
RO                   284  165.973525
RR                    52  150.565962
RS                  6269  120.337453
SC                  4201  124.653578
SE                   390  153.041169
SP                 47820  109.653629
TO                   316  157.529333

# NIVEL 5
#### Identifica los 10 clientes que hayan generado el mayor gasto total en productos. Para cada cliente muestra su identificador, ciudad,  estado y gasto tota

In [237]:
#Agarro el merge hecho en el problema anterior porque ya están juntos orders, order items y customers
df2_nivel5_paso1 = df1_nivel5_paso2.groupby("customer_unique_id")[["price"]].sum().reset_index().sort_values("price",ascending = False).head(10)
df2_nivel5_paso1.merge(customers, on = "customer_unique_id", how = "inner").sort_values("price", ascending = False)[["customer_unique_id","customer_city","customer_state","price"]]

                  customer_unique_id   customer_city customer_state    price
0   0a0a92112bd4c708ca5fde585afaa872  rio de janeiro             RJ  13440.0
1   da122df9eeddfedc1dc1f5349a1a690c        araruama             RJ   7388.0
2   da122df9eeddfedc1dc1f5349a1a690c        araruama             RJ   7388.0
3   763c8b1c9c68a0229c42c9fc6f662b93      vila velha             ES   7160.0
4   dc4802a71eae9be1dd28f5d788ceb526    campo grande             MS   6735.0
5   459bef486812aa25204be022145caa62         vitoria             ES   6729.0
6   ff4159b92c40ebe40454e3e6a7c35ed6         marilia             SP   6499.0
7   4007669dec559734d6f53e029e360987     divinopolis             MG   5934.6
8   eebb5dda148d3893cdaf5b5ca3040ccb            maua             SP   4690.0
9   5d0a2980b292d049061542014e8960bf         goiania             GO   4599.9
10  48e1ac109decbb87765a3eade6854098     joao pessoa             PB   4590.0

# NIVEL 5
#### Determina la puntuación promedio de las reseñas para cada categoría de product

In [238]:
df3_paso2 = order_reviews.merge(order_items, on = "order_id", how = "left")
df3_paso3 = df3_paso2.merge(products, on = "product_id", how = "left")
df3_paso3.groupby("product_category_name")[["review_score"]].mean()

                           review_score
product_category_name
agro_industria_e_comercio      4.000000
alimentos                      4.218182
alimentos_bebidas              4.315412
artes                          3.937198
artes_e_artesanato             4.125000
...                                 ...
sinalizacao_e_seguranca        4.086294
tablets_impressao_imagem       4.123457
telefonia                      3.946867
telefonia_fixa                 3.683206
utilidades_domesticas          4.055019

[73 rows x 1 columns]