# Guía Olist

In [94]:
import pandas as pd

orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
geo = pd.read_csv("olist_geolocation_dataset.csv")
payment = pd.read_csv("olist_order_payments_dataset.csv")

In [95]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [96]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [97]:
order_reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='object')

In [98]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [99]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [100]:
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [101]:
geo.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

In [102]:
payment.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

# 1. De la tabla de pedidos, muestra únicamente order_id, customer_id y order_status.

In [103]:
orders[["order_id","customer_id","order_status"]]

,order_id,customer_id,order_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered
...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered

# 2. Selecciona de productos las columnas product_id, product_category_name y product_weight_g.

In [104]:
products[["product_id","product_category_name","product_weight_g"]]

,product_id,product_category_name,product_weight_g
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,225.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1000.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,154.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,371.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,625.0
...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,12300.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1700.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1400.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,700.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,2083.0

# 3. Filtra los pedidos cuyo estado sea delivered.

In [105]:
entregadas = orders[orders["order_status"] == "delivered"]
entregadas[["order_status"]]

      order_status
0        delivered
1        delivered
2        delivered
3        delivered
4        delivered
...            ...
99436    delivered
99437    delivered
99438    delivered
99439    delivered
99440    delivered

[96478 rows x 1 columns]

# 4. Muestra los artículos cuyo precio sea mayor que 100

In [106]:
mayores_a_100 = order_items[order_items["price"]>100]

In [107]:
mayores_a_100[["product_id","price"]]

                              product_id   price
1       e5f2d52b802189ee658865ca93d83a8f  239.90
2       c777355d18b72b67abbeef9df44fd0fd  199.00
4       ac6c3623068f30de03045865e4e10089  199.90
7       557d850972a7d6f792fd18ae1400d9b6  810.00
8       310ae3c140ff94b03219ad0adc3c778f  145.95
...                                  ...     ...
112635  bee2e070c39f3dd2f6883a17a5f0da45  180.00
112637  bbe7651fef80287a816ead73f065fc4b  229.90
112644  6f0169f259bb0ff432bfff7d829b9946  119.85
112645  4aa6014eceb682077f9dc4bffebc05b0  299.99
112646  32e07fd915822b0765e448c4dd74c828  350.00

[40313 rows x 2 columns]

# 5. Filtra los pagos realizados con credit_card.

In [108]:
payment[payment["payment_type"] == "credit_card"][["order_id","payment_type"]]

                                order_id payment_type
0       b81ef226f3fe1789b1e8b2acac839d17  credit_card
1       a9810da82917af2d9aefd1278f1dcfa0  credit_card
2       25e8ea4e93396b6fa0d3dd708e76c1bd  credit_card
3       ba78997921bbcdc1373bb41e913ab953  credit_card
4       42fdf880ba16b47b59251dd489d4441a  credit_card
...                                  ...          ...
103879  c45067032fd84f4cf408730ff5205568  credit_card
103880  7159096c5aa9be77f7f0c26c01ee9793  credit_card
103882  7b905861d7c825891d6347454ea7863f  credit_card
103883  32609bbb3dd69b3c066a6860554a77bf  credit_card
103884  b8b61059626efa996a60be9bb9320e10  credit_card

[76795 rows x 2 columns]

# 6. Obtén las reseñas con puntuación igual a 5 y muestra sólo el identificador del pedido y la puntuación.

In [109]:
order_reviews[order_reviews["review_score"] == 5][["order_id","review_score"]]

                               order_id  review_score
1      a548910a1c6147796b98fdf73dbeba33             5
2      f9e4b658b201a9f2ecdecbb34bed034b             5
3      658677c97b385a9be170737859d3511b             5
4      8e6bfb81e283fa7e4f11123a3fb894f1             5
6      e48aa0d2dcec3a2e87348811bcfdf22b             5
...                                 ...           ...
99217  48f7ee67313eda32bfcf5b9c1dd9522d             5
99218  d699c734a0b1c8111f2272a3f36d398c             5
99219  2a8c23fee101d4d5662fa670396eb8da             5
99220  22ec9f0669f784db00fa86d035cf8602             5
99221  55d4004744368f5571d1f590031933e4             5

[57328 rows x 2 columns]

# 7. Selecciona los vendedores del estado SP, mostrando identificador, ciudad y estado

In [110]:
sellers[sellers["seller_state"]== "SP"][["seller_id","seller_city","seller_state"]]

                             seller_id        seller_city seller_state
0     3442f8959a84dea7ee197c632cb2df15           campinas           SP
1     d1b65fc7debc3361ea86b5f14c68d2e2         mogi guacu           SP
3     c0f3eea2e14555b6faeea3dd58c1b1c3          sao paulo           SP
4     51a04a8a6bdcb23deccc82b0b80742cf  braganca paulista           SP
7     1b938a7ec6ac5061a66a3766e0e75f90          penapolis           SP
...                                ...                ...          ...
3087  f00f5b35d0abcacbdd863672f4bb2c1a          sao paulo           SP
3088  7bac63f6603d382cc8d0832eb6c100a8          sao paulo           SP
3089  f1fdf2d13186575751aa25876536d85c          sao paulo           SP
3092  74871d19219c7d518d0090283e03c137          sao paulo           SP
3094  9e25199f6ef7e7c347120ff175652c3b            taubate           SP

[1849 rows x 3 columns]

# 8. Filtra los productos cuyo peso sea nulo.

In [111]:
products[products["product_weight_g"].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 9. Muestra pedidos cuya fecha de compra sea posterior al 1 de enero de 2018 (convierte primero la columna a fecha si es necesario)

In [112]:
tiempo = pd.to_datetime(orders["order_purchase_timestamp"])
orders[tiempo > "2018-1-1"]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
12,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18 00:00:00
13,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08 00:00:00
...,...,...,...,...,...,...,...,...
99428,c22a47117b6a87c967b0c278488110c1,6e153567dc52ea59c0498ef5383e9c7a,delivered,2018-06-22 20:53:29,2018-06-22 21:17:45,2018-06-25 17:50:00,2018-07-03 19:48:54,2018-07-23 00:00:00
99430,c81f74e50f0496fa39716cc77cacd460,7b270ebc87c25c8404348c10ff80a80e,delivered,2018-03-04 22:48:38,2018-03-04 23:09:22,2018-03-05 16:15:04,2018-03-13 18:54:32,2018-03-26 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

# 10. En ítems, filtra registros cuyo flete sea mayor que 30 y cuyo precio sea menor que 200.

In [113]:
costo_flete = order_items["freight_value"]
precio_mas = order_items["price"]
order_items[(costo_flete>30) & (precio_mas < 200)]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
22,000f25f4d72195062c040b12dce9a18a,1,1c05e0964302b6cf68ca0d15f326c6ba,7c67e1448b00f6e969d365cea6b010ab,2018-03-21 11:10:11,119.99,44.40
59,00254baeb6c932b0a8aeead91fbd02b5,1,18901878788fec7ddc55e64d1ace8187,e8b4225284fbb02d16f200513f1f395d,2018-05-14 22:14:46,149.90,43.11
73,002b430ff89b3a24c31a1170acbbedea,1,cc47c0863559499f01b4cad750929d10,7a67c85e85bb2ce8582c35f2203ad736,2017-06-26 22:10:14,199.99,65.56
80,002f98c0f7efd42638ed6100ca699b42,1,d41dc2f2979f52d75d78714b378d4068,7299e27ed73d2ad986de7f7c77d919fa,2017-08-10 09:30:15,8.99,32.57
85,00324b3eda39ba5ecce3945823e3594c,1,54e5063e43f27f747d592eb24e913150,0dd184061fb0eaa7ca37932c68ab91c5,2018-04-17 09:12:11,76.00,34.07
...,...,...,...,...,...,...,...
112635,fff8287bbae429a99bb7e8c21d151c41,2,bee2e070c39f3dd2f6883a17a5f0da45,4e922959ae960d389249c378d1c939f5,2018-03-27 12:29:22,180.00,48.14
112640,fffb9224b6fc7c43ebb0904318b10b5f,1,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,43423cdffde7fda63d0414ed38c11a73,b1fc4f64df5a0e8b6913ab38803c57a9,2017-11-03 02:55:58,55.00,34.19

# 11. Encuentra pedidos cuyo estado sea canceled o unavailable.

In [114]:
orders[(orders["order_status"]== "canceled")|(orders["order_status"]=="unavailable")]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
266,8e24261a7e58791d10cb1bf9da94df5c,64a254d30eed42cd0e6c36dddb88adf0,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaN,NaN,2017-12-05 00:00:00
397,1b9ecfe83cdc259250e1a8aca174f0ad,6d6b50b66d79f80827b6d96751528d30,canceled,2018-08-04 14:29:27,2018-08-07 04:10:26,NaN,NaN,2018-08-14 00:00:00
586,c272bcd21c287498b4883c7512019702,9582c5bbecc65eb568e2c1d839b5cba1,unavailable,2018-01-31 11:31:37,2018-01-31 14:23:50,NaN,NaN,2018-02-16 00:00:00
613,714fb133a6730ab81fa1d3c1b2007291,e3fe72696c4713d64d3c10afe71e75ed,canceled,2018-01-26 21:34:08,2018-01-26 21:58:39,2018-01-29 22:33:25,NaN,2018-02-22 00:00:00
687,37553832a3a89c9b2db59701c357ca67,7607cd563696c27ede287e515812d528,unavailable,2017-08-14 17:38:02,2017-08-17 00:15:18,NaN,NaN,2017-09-05 00:00:00
...,...,...,...,...,...,...,...,...
99252,aaab15da689073f8f9aa978a390a69d1,df20748206e4b865b2f14a5eabbfcf34,unavailable,2018-01-16 14:27:59,2018-01-17 03:37:34,NaN,NaN,2018-02-06 00:00:00
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaN,2018-10-01 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00

# 12. Selecciona productos cuyo nombre de categoría contenga la cadena beleza, sin distinguir mayúsculas y minúsculas. Considera los nulos

In [115]:
products["product_category_name"].unique()

array(['perfumaria', 'artes', 'esporte_lazer', 'bebes',
       'utilidades_domesticas', 'instrumentos_musicais', 'cool_stuff',
       'moveis_decoracao', 'eletrodomesticos', 'brinquedos',
       'cama_mesa_banho', 'construcao_ferramentas_seguranca',
       'informatica_acessorios', 'beleza_saude', 'malas_acessorios',
       'ferramentas_jardim', 'moveis_escritorio', 'automotivo',
       'eletronicos', 'fashion_calcados', 'telefonia', 'papelaria',
       'fashion_bolsas_e_acessorios', 'pcs', 'casa_construcao',
       'relogios_presentes', 'construcao_ferramentas_construcao',
       'pet_shop', 'eletroportateis', 'agro_industria_e_comercio', nan,
       'moveis_sala', 'sinalizacao_e_seguranca', 'climatizacao',
       'consoles_games', 'livros_interesse_geral',
       'construcao_ferramentas_ferramentas',
       'fashion_underwear_e_moda_praia', 'fashion_roupa_masculina',
       'moveis_cozinha_area_de_servico_jantar_e_jardim',
       'industria_comercio_e_negocios', 'telefonia_fixa',
       'construcao_ferramentas_iluminacao', 'livros_tecnicos',
       'eletrodomesticos_2', 'artigos_de_festas', 'bebidas',
       'market_place', 'la_cuisine', 'construcao_ferramentas_jardim',
       'fashion_roupa_feminina', 'casa_conforto', 'audio',
       'alimentos_bebidas', 'musica', 'alimentos',
       'tablets_impressao_imagem', 'livros_importados',
       'portateis_casa_forno_e_cafe', 'fashion_esporte',
       'artigos_de_natal', 'fashion_roupa_infanto_juvenil',
       'dvds_blu_ray', 'artes_e_artesanato', 'pc_gamer', 'moveis_quarto',
       'cine_foto', 'fraldas_higiene', 'flores', 'casa_conforto_2',
       'portateis_cozinha_e_preparadores_de_alimentos',
       'seguros_e_servicos', 'moveis_colchao_e_estofado',
       'cds_dvds_musicais'], dtype=object)

In [116]:
products[products["product_category_name"].str.contains("beleza", case = False, na = False)][["product_id","product_category_name"]]

                             product_id product_category_name
22     e3e020af31d4d89d2602272b315c3f6e          beleza_saude
49     c5d8079278e912d7e3b6beb48ecb56e8          beleza_saude
62     36555a2f528d7b2a255c504191445d39          beleza_saude
75     e586ebb6022265ae1eea38f46ffe3ead          beleza_saude
80     75b4372e69a42f8ae1d908c076f547b2          beleza_saude
...                                 ...                   ...
32895  ff0ba1ffc67724ddc6db331bd417ef67          beleza_saude
32915  d790fcd60d4743d309fedf7e7bb4c902          beleza_saude
32917  4419a003d42a243227478f2a949722d8          beleza_saude
32918  2636a9812d151c718b53387171ce08be          beleza_saude
32926  c1cf541d5b33a4b04ddc1c3be7aa1c86          beleza_saude

[2444 rows x 2 columns]

# 13. En la tabla de clientes, normaliza los nombres de ciudad: elimina espacios al inicio/final y conviértelos a minúsculas. Muestra algunas filas antes y después.

In [117]:
customers["customer_city"] = customers["customer_city"].str.strip().str.lower()

In [118]:
customers[["customer_city"]]

               customer_city
0                     franca
1      sao bernardo do campo
2                  sao paulo
3            mogi das cruzes
4                   campinas
...                      ...
99436              sao paulo
99437        taboao da serra
99438              fortaleza
99439                 canoas
99440                  cotia

[99441 rows x 1 columns]

# 14. En la tabla de vendedores, crea una columna con el nombre de ciudad en mayúsculas.

In [119]:
sellers["ciudad_mayusculas"] = sellers["seller_city"].str.upper()

In [120]:
sellers

,seller_id,seller_zip_code_prefix,seller_city,seller_state,ciudad_mayusculas
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,CAMPINAS
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,MOGI GUACU
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,RIO DE JANEIRO
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP,SAO PAULO
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,BRAGANCA PAULISTA
...,...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR,SARANDI
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC,PALHOCA
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP,SAO PAULO
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,PELOTAS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP,TAUBATE

# 15. Cuenta cuántos valores nulos hay en cada columna de la tabla de productos

In [121]:
products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

# 16. Elimina las filas de productos que no tengan product_category_name; reporta cuántas filas quedaron

In [122]:
products.dropna(subset = "product_category_name")
#quedaron 32341 filas

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

# 17. En productos, reemplaza los valores nulos de product_weight_g por la mediana de esa columna.

In [123]:
mediana_del_peso = products["product_weight_g"].median()
mediana_del_peso

np.float64(700.0)

In [124]:
products[["product_weight_g"]].fillna(mediana_del_peso)

       product_weight_g
0                 225.0
1                1000.0
2                 154.0
3                 371.0
4                 625.0
...                 ...
32946           12300.0
32947            1700.0
32948            1400.0
32949             700.0
32950            2083.0

[32951 rows x 1 columns]

# 18. En reseñas, reemplaza los comentarios nulos por la cadena ” y cuenta cuántos comentarios quedan vacíos.

In [125]:
order_reviews[["review_comment_message"]].fillna("")

                                  review_comment_message
0
1
2
3                  Recebi bem antes do prazo estipulado.
4      Parabéns lojas lannister adorei comprar pela I...
...                                                  ...
99219
99220
99221  Excelente mochila, entrega super rápida. Super...
99222
99223  meu produto chegou e ja tenho que devolver, po...

[99224 rows x 1 columns]

In [126]:
(order_reviews["review_comment_message"].fillna("")=="").sum()

np.int64(58247)

# 19. Filtra pedidos entregados que tengan fecha de entrega real no nulo

In [127]:
orders[(orders["order_status"]== "delivered")&(orders["order_delivered_customer_date"].fillna("")!="")]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

# 20. En ítems, crea valor_total_item como la suma de precio y flete. Muestra order_id, price, freight_value y la nueva columna

In [128]:
order_items["valor_total_items"] = order_items["price"] + order_items["freight_value"]
order_items[["order_id","price","freight_value","valor_total_items"]]

,order_id,price,freight_value,valor_total_items
0,00010242fe8c5a6d1ba2dd792cb16214,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,18.14,218.04
...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,299.99,43.41,343.40
112646,fffcd46ef2263f404302a634eb57f7eb,350.00,36.53,386.53
112647,fffce4705a9662cd70adb13d4a31832d,99.90,16.95,116.85
112648,fffe18544ffabc95dfada21779c9644f,55.99,8.72,64.71
112649,fffe41c64501cc87c801fd61db3f6244,43.00,12.79,55.79

# 21. Calcula el precio promedio, mínimo y máximo de los artículos

In [129]:
order_items["price"].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

# 22. Agrupa los ítems por seller_id y calcula cuántos artículos vendió cada vendedor.

In [130]:
order_items.groupby("seller_id")[["order_item_id"]].count().sort_values(by="order_item_id")

                                  order_item_id
seller_id
001e6ad469a905060d959994f1b41e4f              1
fa5fdc4e4bb6bd1009ad0e4ac4096562              1
6ebf4eceee4dd9847201c82e77ef8123              1
6e85dc5ecd97a61094b89b046a509d8e              1
c092292535a57dacd95a8765f5518f87              1
...                                         ...
da8622b14eb17ae2831f4ac5b9dab84a           1551
cc419e0650a3c5ba77189a1882b7556a           1775
1f50f920176fa81dab994f9023523100           1931
4a3ca9315b744ce9f8e9374361493884           1987
6560211a19b47992c3666cc44a7e94c0           2033

[3095 rows x 1 columns]

# 23. Agrupa los pagos por tipo y calcula el valor total pagado por cada tipo

In [131]:
payment.groupby("payment_type")[["payment_value"]].sum()

              payment_value
payment_type
boleto           2869361.27
credit_card     12542084.19
debit_card        217989.79
not_defined            0.00
voucher           379436.87

# 24. Calcula el promedio de puntuación de reseñas por review_score.

In [132]:
order_reviews["review_score"].mean()

np.float64(4.08642062404257)

# 25. Crea en pedidos una columna duracion_entrega_dias como diferencia entre fecha de entrega real y fecha de compra. Calcula la mediana sólo para pedidos con ambas fechas disponible

In [133]:
orders["order_purchase_timestamp"] = pd.to_datetime(orders["order_purchase_timestamp"])
orders["order_delivered_customer_date"] = pd.to_datetime(orders["order_delivered_customer_date"])
orders["duracion_entrega_dias"] = ((orders["order_delivered_customer_date"]) - (orders["order_purchase_timestamp"])).dropna()
((orders["duracion_entrega_dias"]).dt.days).median()

np.float64(10.0)

# 26. Crea una columna booleana que indique si el flete supera el 20 % del precio del artículo

In [134]:
order_items["Mas_20%"] = order_items["freight_value"]>(order_items["price"]*0.20)
order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,valor_total_items,Mas_20%
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,True
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,False
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,False
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,True
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,False
...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,343.40,False
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,386.53,False
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,116.85,False
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,64.71,False
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,55.79,True

# 27. Agrupa los productos por categoría y calcula el peso promedio, excluyendo los pesos nulo

In [135]:
products.groupby("product_category_name")[["product_weight_g"]].mean()

                           product_weight_g
product_category_name
agro_industria_e_comercio       5263.405405
alimentos                        923.414634
alimentos_bebidas               1307.932692
artes                           1691.763636
artes_e_artesanato              1164.578947
...                                     ...
sinalizacao_e_seguranca         2969.817204
tablets_impressao_imagem         381.444444
telefonia                        236.506173
telefonia_fixa                   660.827586
utilidades_domesticas           3020.793576

[73 rows x 1 columns]

# 28. Agrupa vendedores por estado y cuenta cuántos vendedores hay en cada estado. Ordena el resultado de mayor a menor

In [136]:
sellers.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state',
       'ciudad_mayusculas'],
      dtype='object')

In [137]:
sellers.groupby("seller_state")[["seller_id"]].nunique()

              seller_id
seller_state
AC                    1
AM                    1
BA                   19
CE                   13
DF                   30
ES                   23
GO                   40
MA                    1
MG                  244
MS                    5
MT                    4
PA                    1
PB                    6
PE                    9
PI                    1
PR                  349
RJ                  171
RN                    5
RO                    2
RS                  129
SC                  190
SE                    2
SP                 1849

# 29. En pagos, crea valor_por_cuota dividiendo payment_value entre payment_installments, evitando divisiones entre cero o nulos.

In [138]:
sin_0 = payment["payment_installments"] > 0
payment.loc[sin_0, "valor_por_cuota"] = payment["payment_value"] / payment["payment_installments"]
payment

,order_id,payment_sequential,payment_type,payment_installments,payment_value,valor_por_cuota
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,12.41625
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,24.39000
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,65.71000
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,13.47250
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,64.22500
...,...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31,363.31000
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80,48.40000
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77,47.77000
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54,73.90800
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58,191.58000

# 30. Agrupa las reseñas por puntuación y calcula el número de reseñas y el promedio de longitud de los comentarios, tratando comentarios nulos como texto vacío

In [139]:
order_reviews["largo"] = order_reviews["review_comment_message"].fillna("").str.len()
order_reviews.groupby("review_score").agg({"review_id":"count","largo":"mean"})

              review_id      largo
review_score
1                 11424  76.504902
2                  3151  65.926373
3                  8179  36.240494
4                 19142  19.272803
5                 57328  18.586188

# 41. Para cada estado del cliente, calcula el número de pedidos entregados y el porcentaje que representan respecto del total de pedidos de ese estado

In [140]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'duracion_entrega_dias'],
      dtype='object')

In [141]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [142]:
paso1 = orders.merge(customers, on = "customer_id", how = "left")
paso1["entregados"] = paso1["order_status"] == "delivered"
paso2 = paso1.groupby("customer_state").agg({"entregados":["sum","count"]})
paso2["porcentaje"] = ((paso2["entregados","sum"])/(paso2["entregados","count"]))*100
paso2[[("entregados","sum"),("porcentaje","")]]

               entregados porcentaje
                      sum
customer_state
AC                     80  98.765432
AL                    397  96.125908
AM                    145  97.972973
AP                     67  98.529412
BA                   3256  96.331361
CE                   1279  95.733533
DF                   2080  97.196262
ES                   1995  98.130841
GO                   1957  96.881188
MA                    717  95.983936
MG                  11354  97.584873
MS                    701  98.041958
MT                    886  97.684675
PA                    946  97.025641
PB                    517  96.455224
PE                   1593  96.428571
PI                    476  96.161616
PR                   4923  97.581764
RJ                  12350  96.093993
RN                    474  97.731959
RO                    243  96.047431
RR                     41  89.130435
RS                   5345  97.786315
SC                   3546  97.497938
SE                    335  95.714286
SP                  40501  97.017678
TO                    274  97.857143

# 42. Encuentra las 10 categorías con mayor número de artículos vendidos. Une ítems con productos y excluye categorías nulas

In [143]:
paso1 = order_items.merge(products, on = "product_id", how = "left")
paso2 = paso1.groupby("product_category_name")[["order_id"]].count()
paso2.sort_values("order_id", ascending = False)

                               order_id
product_category_name
cama_mesa_banho                   11115
beleza_saude                       9670
esporte_lazer                      8641
moveis_decoracao                   8334
informatica_acessorios             7827
...                                 ...
cds_dvds_musicais                    14
la_cuisine                           14
pc_gamer                              9
fashion_roupa_infanto_juvenil         8
seguros_e_servicos                    2

[73 rows x 1 columns]

# 43. Calcula el ingreso por pedido como la suma de price de sus artículos. Une el resultado con pedidos y muestra los 10 pedidos de mayor ingreso

In [144]:
paso1 = (order_items.groupby("order_id")[["price"]].sum()).sort_values("price", ascending=False)
(paso1.reset_index().merge(orders, on = "order_id", how = "left")).head(10)

,order_id,price,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,duracion_entrega_dias
0,03caa2c082116e1d31e67e9ae3700499,13440.0,1617b1357756262bfa56ab541c47bc16,delivered,2017-09-29 15:24:52,2017-10-02 15:28:20,2017-10-10 15:43:17,2017-10-17 18:22:29,2017-10-23 00:00:00,18 days 02:57:37
1,736e1922ae60d0d6a89247b851902527,7160.0,ec5b2ba62e574342386871631fafd3fc,delivered,2018-07-15 14:49:44,2018-07-17 04:31:36,2018-07-20 13:09:00,2018-07-26 22:03:06,2018-08-02 00:00:00,11 days 07:13:22
2,0812eb902a67711a1cb742b3cdaa65ae,6735.0,c6e2731c5b391845f6800c97401a43a9,delivered,2017-02-12 20:37:36,2017-02-12 20:45:12,2017-02-16 09:23:13,2017-03-03 14:23:18,2017-03-09 00:00:00,18 days 17:45:42
3,fefacc66af859508bf1a7934eab1e97f,6729.0,f48d464a0baaea338cb25f816991ab1f,delivered,2018-07-25 18:10:17,2018-07-27 04:05:13,2018-08-03 14:42:00,2018-08-15 14:57:50,2018-08-10 00:00:00,20 days 20:47:33
4,f5136e38d1a14a4dbd87dff67da82701,6499.0,3fd6777bbce08a352fddd04e4a7cc8f6,delivered,2017-05-24 18:14:34,2017-05-26 02:45:17,2017-05-26 11:20:47,2017-06-05 17:09:48,2017-06-28 00:00:00,11 days 22:55:14
5,2cc9089445046817a7539d90805e6e5a,5934.6,05455dfa7cd02f13d132aa7a6a9729c6,delivered,2017-11-24 11:03:35,2017-11-28 12:55:46,2017-12-06 11:52:14,2017-12-13 12:16:02,2017-12-22 00:00:00,19 days 01:12:27
6,a96610ab360d42a2e5335a3998b4718a,4799.0,df55c14d1476a9a3467f131269c2477f,delivered,2017-04-01 15:58:40,2017-04-03 13:25:18,2017-04-11 15:10:34,2017-04-17 11:04:45,2017-05-02 00:00:00,15 days 19:06:05
7,199af31afc78c699f0dbf71fb178d4d4,4690.0,24bbf5fd2f2e1b359ee7de94defc4a15,delivered,2017-04-18 18:50:13,2017-04-19 15:50:15,2017-04-25 13:39:59,2017-05-07 10:42:39,2017-05-15 00:00:00,18 days 15:52:26
8,b4c4b76c642808cbe472a32b86cddc95,4599.9,e0a2412720e9ea4f26c1ac985f6a7358,canceled,2018-07-12 12:08:36,2018-07-12 12:25:53,NaN,NaT,2018-08-01 00:00:00,NaT
9,8dbc85d1447242f3b127dda390d56e19,4590.0,3d979689f636322c62418b6346b1c6d2,delivered,2018-06-22 12:23:19,2018-06-22 12:36:36,2018-06-22 13:00:00,2018-07-06 01:08:30,2018-07-17 00:00:00,13 days 12:45:11

# 44. Calcula el gasto total por cliente único sumando el precio y el flete de sus artículos. Une ítems con clientes a través de pedidos y ordena de mayor a menor

In [145]:
paso1 = orders.merge(order_items, on = "order_id", how = "left")
paso2 = paso1.merge(customers, on = "customer_id", how = "left")
paso2.groupby("customer_unique_id")[["valor_total_items"]].sum().sort_values("valor_total_items", ascending = False)

                                  valor_total_items
customer_unique_id
0a0a92112bd4c708ca5fde585afaa872           13664.08
da122df9eeddfedc1dc1f5349a1a690c            7571.63
763c8b1c9c68a0229c42c9fc6f662b93            7274.88
dc4802a71eae9be1dd28f5d788ceb526            6929.31
459bef486812aa25204be022145caa62            6922.21
...                                             ...
f4aedee3d8eb400162acc5b1dae159c3               0.00
99e1c1df6a737fea3658ca705b8f374d               0.00
39f31c1aae7c88de15521a33a3d5e44c               0.00
004ad212c650c96c8a48f30855a7bcb8               0.00
6fe279814d16772b218b116cd015e1c4               0.00

[96096 rows x 1 columns]

# 45. Compara el precio promedio de artículos entre pedidos entregados y pedidos cancelados. Une ítems con pedidos y explica cómo se manejan los estados ausente

In [ ]:
paso1df45 = order_items.merge(orders, on = "order_id", how = "left")
paso2 = paso1df45[paso1df45["order_status"]== "canceled"]
paso2["price"].mean()

np.float64(175.71083025830256)

In [147]:
paso1df45 = order_items.merge(orders, on = "order_id", how = "left")
paso2 = paso1df45[paso1df45["order_status"]== "delivered"]
paso2["price"].mean()

np.float64(119.98056308247958)

# 46. Para cada vendedor, calcula número de pedidos distintos, número de artículos, precio total y flete total. Evita contar varias veces un pedido dentro de cada vendedo

In [150]:
order_items.nunique()

order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
valor_total_items      29149
Mas_20%                    2
dtype: int64